import { Dimensions } from './types';
export declare const BLUR_FILTER_RADIUS = 15;
export declare const DEBOUNCE_COUNT = 2;
export declare const MASK_BLUR_RADIUS = 5;
export declare const HISTORY_COUNT_MULTIPLIER = 3;
export declare const PERSON_PROBABILITY_THRESHOLD = 0.4;
export declare const MODEL_NAME = "selfie_segmentation_landscape.tflite";
export declare const TFLITE_LOADER_NAME = "tflite-1-0-0.js";
export declare const TFLITE_SIMD_LOADER_NAME = "tflite-simd-1-0-0.js";
export declare const WASM_INFERENCE_DIMENSIONS: Dimensions;
